/* --------------------------------------------------------------------------------------------------------------

// Tipos de Função

//Declarativas
function Funcao(){
    console.log('Aoba,bão?')
}

Funcao(); */

/* --------------------------------------------------------------------------------------------------------------

// Expressão de Função 

//Com nomeação
var funcao = function funcao(){
    console.log('Aoba Ricardito')
}

funcao();

//Sem nomeação
var funcao = function(){
    console.log('Aoba Ricardito')
}

funcao();

// Arrow Function 
var funcao = () => {
    console.log('Soy hermoso')
}

funcao(); */
